// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using data.Data;

#nullable disable

namespace data.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("data.Models.Student", b =>
                {
                    b.Property<int>("std_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("std_id"));

                    b.Property<string>("std_class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("std_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("std_section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("std_id");

                    b.ToTable("tbl_students");
                });
#pragma warning restore 612, 618
        }
    }
}
